baseurl = "https://shaaf.dev/keycloak-tutorial"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Keycloak tutorial"
canonifyurls = true
paginate = 10

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[author]
  name = "Shaaf, Syed"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "A hands-on introduction to keycloak"
  Author = "Shaaf, Syed"
  Ganalytics = "XX-00000000-0"
  themeVariant = "blue"
  disableInlineCopyToClipBoard = "false"

## Use those parameters with {{< param "param_name" >}}
  deployment = "production"

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Homepage"
url = "https://shaaf.dev/keycloak-tutorial"
weight = 10

[markup]
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]


[security]
#enableInlineShortcodes = false

[security.exec]
allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
getenv = ["^HUGO_"]

[security.http]
methods = ["(?i)GET|POST"]
urls = [".*"]